data_dir: "C:/Users/nroy/Pictures/NCT-CRC-HE-100K/NCT-CRC-HE-100K"
output_dir: "C:/Users/nroy/Pictures/Dataset_Split"
classes:
  - "ADI"
  - "BACK"
  - "DEB"
  - "LYM"
  - "MUC"
  - "MUS"
  - "NORM"
  - "STR"
  - "TUM"
splits:
  test_size: 0.2
  val_size: 0.1
  random_state: 42